import Head from 'next/head'
import About from '../components/about'
import {Main} from '../components/main'
import Navbar from '../components/navbar'
import Partners from '../components/partners'
import Speakers from '../components/speakers'

export default function Home() {
  return (
    <div className='md:mr-0'>
      <Head>
        <title>Polygon RoadShow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Main/>
      <About/>
      <Speakers/>
      <Partners/>
    </div>
  )
}
